name: Build Project DotNet

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.103' # SDK Version to use.
      - name: build project
        run: | 
          dotnet restore
          cd 'RestoreExternalNugetServer'
          dotnet build
